services:
  # log-collector:
  #   build:
  #     context: ./log-collector
  #     dockerfile: Dockerfile
  #   container_name: log-collector
  #   restart: unless-stopped
  #   ports:
  #     - "4000:4000"
  #   networks:
  #     - gateway-net

  # extra_hosts:
    # - "host.docker.internal:host-gateway"
  kong:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev

    container_name: kong-konnect

    restart: unless-stopped

    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001" # Admin API port for status and other admin tasks

    extra_hosts:
      - "host.docker.internal:host-gateway"

    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  auth-service:
    container_name: auth
    build: 
      context : ./auth
      dockerfile: Dockerfile.dev
    depends_on :
      - mongo-auth
    # image: auth
    ports:
      - "3000:3000"
    # env_file: ./auth/.env
    develop:
      watch:
        - path: ./auth/package.*.json
          target: ./app
          action: rebuild
        - path: ./auth
          target: /app
          action: sync
  checkout-service:
    container_name: checkout
    build: 
      context:  ./checkout
      dockerfile: Dockerfile.dev
    depends_on :
      -  mongodb-checkout
    # image: checkout
    ports:
      - "2000:2000"         # NOT exposed to host, only nginx can reach it
    # env_file: ./checkout/.env
    develop:
      watch:
        - path: ./checkout/package.*.json
          target: ./app
          action: rebuild
        - path: ./checkout
          target: /app
          action: sync
  mongo-auth:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_auth_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234

  mongodb-checkout:
    image: mongo:latest
    container_name: mongodb-checkout
    ports:
      - "27018:27017"
    volumes:
      - mongodb_checkout_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./frontend/package.*.json
          target: /app
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
  mongodb_auth_data:
  mongodb_checkout_data:
