services:
  nginx:
    build: 
      context: ./gateway
      dockerfile: Dockerfile.dev
    # image: nginx
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - checkout-service
    container_name: nginx

  auth-service:
    container_name: auth
    build: 
      context : ./auth
      dockerfile: Dockerfile.dev
    # image: auth
    expose:
      - "3000"
    # env_file: ./auth/.env
    develop:
      watch:
        - path: ./auth/package.*.json
          target: ./app
          action: rebuild
        - path: ./auth
          target: /app
          action: sync
  checkout-service:
  
    container_name: checkout
    build: 
      context:  ./checkout
      dockerfile: Dockerfile.dev

    # image: checkout
    expose:
      - "4000"         # NOT exposed to host, only nginx can reach it
    # env_file: ./checkout/.env
    develop:
      watch:
        - path: ./checkout/package.*.json
          target: ./app
          action: rebuild
        - path: ./checkout
          target: /app
          action: sync
  mongo-auth:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_auth_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234

  mongodb-checkout:
    image: mongo:latest
    container_name: mongodb-checkout
    ports:
      - "27018:27017"
    volumes:
      - mongodb_checkout_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234

volumes:
  mongodb_auth_data:
  mongodb_checkout_data: