services:
  nginx:
    build: 
      context: ./gateway
      dockerfile: Dockerfile.dev
    # image: nginx
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - checkout-service
    container_name: nginx

  auth-service:
    container_name: auth
    build: 
      context : ./auth
      dockerfile: Dockerfile.dev
    # image: auth
    expose:
      - "3000"
    # env_file: ./auth/.env
    develop:
      watch:
        - path: ./auth/package.*.json
          target: ./app
          action: rebuild
        - path: ./auth
          target: /app
          action: sync
  checkout-service:
  
    container_name: checkout
    build: 
      context:  ./checkout
      dockerfile: Dockerfile.dev

    # image: checkout
    expose:
      - "4000"         # NOT exposed to host, only nginx can reach it
    # env_file: ./checkout/.env
    develop:
      watch:
        - path: ./checkout/package.*.json
          target: ./app
          action: rebuild
        - path: ./checkout
          target: /app
          action: sync
