FROM kong/kong-gateway:3.14

USER root

# نسخ الملفات
# COPY ./config/kong.yml /etc/kong/kong.yml
COPY cluster.crt /etc/kong/certs/cluster.crt
COPY cluster.key /etc/kong/certs/cluster.key

# صلاحيات
RUN chmod 644 /etc/kong/certs/cluster.crt && \
    chmod 640 /etc/kong/certs/cluster.key && \
    chown kong:kong /etc/kong/certs/cluster.crt && \
    chown kong:kong /etc/kong/certs/cluster.key

# إعدادات Konnect Data Plane
ENV KONG_DATABASE=off
ENV KONG_ROLE=data_plane
ENV KONG_VITALS=off
ENV KONG_ADMIN_LISTEN=0.0.0.0:8001
ENV KONG_CLUSTER_MTLS=pki

ENV KONG_CLUSTER_CONTROL_PLANE=7326248e36.us.cp.konghq.com:443
ENV KONG_CLUSTER_SERVER_NAME=7326248e36.us.cp.konghq.com

ENV KONG_CLUSTER_TELEMETRY_ENDPOINT=7326248e36.us.tp.konghq.com:443
ENV KONG_CLUSTER_TELEMETRY_SERVER_NAME=7326248e36.us.tp.konghq.com

# 👇 أهم نقطة: paths وليس محتوى
ENV KONG_CLUSTER_CERT=/etc/kong/certs/cluster.crt
ENV KONG_CLUSTER_CERT_KEY=/etc/kong/certs/cluster.key

ENV KONG_LUA_SSL_TRUSTED_CERTIFICATE=system
ENV KONG_TLS_CERTIFICATE_VERIFY=off

ENV KONG_KONNECT_MODE=on
ENV KONG_ROUTER_FLAVOR=expressions
USER kong