FROM openresty/openresty:alpine

# Install luarocks + lua-resty-jwt
RUN apk add --no-cache luarocks \
  && luarocks install lua-resty-jwt

# Copy nginx config
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf

# Copy Lua scripts
COPY lua/ /etc/nginx/lua/

# Copy public key (never private.pem)
COPY keys/public.pem /etc/nginx/keys/public.pem

EXPOSE 80
