events { }

http {

    upstream auth_service {
        server auth:3000;
    }

    upstream checkout_service {
        server checkout:4000;
    }

    server {
        listen 80;
        server_name localhost;

        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /checkout/ {
            proxy_pass http://checkout_service/;
            proxy_set_header Host $host;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}