_format_version: "3.0"

services:

  - name: frontend-service
    url: http://host.docker.internal:5173

    routes:
      - name: frontend-route
        paths:
          - /
        strip_path: false
# ------------------------------------------
  - name: auth-service
    url: http://host.docker.internal:3000
    
    routes:
      - name: auth-route
        paths:
          - /api/auth
        strip_path: true
# ------------------------------------------
  - name: checkout-service
    url: http://host.docker.internal:4000
    routes:
      - name: checkout-route
        paths:
          - /api/checkout
        strip_path: true
#-------------------------------------------
plugins:
      - name: ip-restriction
        config:
          allow:
            - 10.0.0.0/8        # VPC / pod network
            - 172.16.0.0/12     # Docker bridge
            - 192.168.0.0/16    # local dev
      # - name: request-termination
      #   config:
      #     status_code: 401
      #     message: '"Error - Authentication required"'
      - name: request-transformer
        config:
           remove:
              headers:
                - X-Admin-Override       # client trying to fake admin
                - X-Internal-Request     # client trying to fake internal
                - Authorization   
           add:
              headers:
              - X-Gateway-Source:kong        # upstream checks this exists
              - X-Internal-Request:true
      - name : request-termination
